defaults:
  - env/libero_10@env.train
  - env/libero_10@env.eval
  - model/pi0_5@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "libero_10_noise_sac_openpi05"
    logger_backends: ["wandb"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: 40

  resume_dir: null # Optional: path to a saved checkpoint directory, such as 'checkpoints/global_step_10'. If not None, it will be used to resume training.
  ckpt_path: null 

algorithm:
  loss_type: noise_sac

  replay_buffer:
    enable_cache: True
    cache_size: 1000
    sample_window_size: 1000
    min_buffer_size: 50

env:
  group_name: "EnvGroup"
  enable_offload: False

  train:
    total_num_envs: 3
    max_episode_steps: 480 # max episode steps for truncation
    max_steps_per_rollout_epoch: 480
    reward_coef: ${algorithm.reward_coef}
    group_size: ${algorithm.group_size}
  eval:
    total_num_envs: 32
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 480
    max_steps_per_rollout_epoch: 480
    group_size: 1
    use_fixed_reset_state_ids: True
    is_eval: True
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  recompute_logprobs: False
  unnorm_key: libero_10
  enable_offload: False
  pipeline_stage_num: 1

  model:
    model_path: "/home/i53/student/gorhan/Masterarbeit/RLinf/RLinf-Pi05-LIBERO-SFT"
    precision: ${actor.model.precision}
    encoder_config:
      model_path: "/home/i53/student/gorhan/Masterarbeit/RLinf/RLinf-ResNet10-pretrained"
      ckpt_name: "resnet10_pretrained.pt"
    openpi:
      use_dsrl_sac: True
    # precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 128
  global_batch_size: 2048 # maximum : global batch size = micro batch size * actor num_processes.
  seed: 42
  enable_offload: False

  # Override the default values in model/pi0_5
  model:
    model_path: "/home/i53/student/gorhan/Masterarbeit/RLinf/RLinf-Pi05-LIBERO-SFT"
    model_type: "noise_sac"
    encoder_config:
      model_path: "/home/i53/student/gorhan/Masterarbeit/RLinf/RLinf-ResNet10-pretrained"
      ckpt_name: "resnet10_pretrained.pt"
    num_steps: 10
    num_q_heads: 10
    use_dsrl_sac: True

  optim:
    lr: 5.0e-6
    value_lr: 1.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    clip_grad: 1.0
    weight_decay: 0.01

  # Override the default values in training_backend/fsdp
  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    gradient_checkpointing: False # for openpi, gradient checkpointing is not supported, please do not change this value
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}
    
reward:
  use_reward_model: False

critic:
  use_critic_model: False