model_type: "noise_policy_openpi"

model_path: ""

precision: null

action_dim: 32
num_action_chunks: 1
num_images_in_input: 1 # for noise policy and critic see dsrl
image_size: [3, 64, 64] # see dsrl


chunk_critic: False

# LoRA settings
is_lora: False
lora_rank: 32


openpi:
  config_name: "pi05_libero"
  num_images_in_input: 2 # see dsrl, wrist image and agentview image from libero
  action_chunk: ${actor.model.num_action_chunks}


encoder_config:
  model_path: "/path/to/model/resnet"
  ckpt_name: "resnet10_pretrained.pt"