model_type: "noise_policy_openpi"

model_path: ""

precision: null

action_dim: 7
num_action_chunks: 50
num_images_in_input: 2
image_size: [3, 128, 128]
state_dim: 29
state_latent_dim: 64

chunk_critic: False


openpi:
  config_name: "pi05_libero"
  num_images_in_input: ${actor.model.num_images_in_input}
  action_chunk: ${actor.model.num_action_chunks}


encoder_config:
  model_path: "/path/to/model/resnet"
  ckpt_name: "resnet10_pretrained.pt"